In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/creditcard.csv")
data

       Time        V1        V2        V3  ...       V27       V28  Amount  Class
0         0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62    0.0
1         0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69    0.0
2         1 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66    0.0
3         1 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50    0.0
4         2 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99    0.0
...     ...       ...       ...       ...  ...       ...       ...     ...    ...
9960  14837  1.286884 -0.124610  0.148283  ... -0.084116 -0.022744   12.18    0.0
9961  14854  1.318742  0.496408  0.114876  ... -0.046154  0.017304    1.78    0.0
9962  14857  1.241757  0.419587  0.806183  ... -0.051084  0.017208    1.29    0.0
9963  14861  1.304800 -0.052885  0.415235  ... -0.099851 -0.015404    4.72    0.0
9964  14864 -1.747939  3.712444       NaN  ...       NaN       NaN     NaN    NaN

[9965 rows x 31 columns]

In [ ]:
data.isna().sum().sum()

28

In [ ]:
import re

In [ ]:
data.fillna(data.mean(),inplace=True)
data

       Time        V1        V2  ...       V28      Amount     Class
0         0 -1.359807 -0.072781  ... -0.021053  149.620000  0.000000
1         0  1.191857  0.266151  ...  0.014724    2.690000  0.000000
2         1 -1.358354 -1.340163  ... -0.059752  378.660000  0.000000
3         1 -0.966272 -0.185226  ...  0.061458  123.500000  0.000000
4         2 -1.158233  0.877737  ...  0.215153   69.990000  0.000000
...     ...       ...       ...  ...       ...         ...       ...
9960  14837  1.286884 -0.124610  ... -0.022744   12.180000  0.000000
9961  14854  1.318742  0.496408  ...  0.017304    1.780000  0.000000
9962  14857  1.241757  0.419587  ...  0.017208    1.290000  0.000000
9963  14861  1.304800 -0.052885  ... -0.015404    4.720000  0.000000
9964  14864 -1.747939  3.712444  ...  0.003051   62.968359  0.003814

[9965 rows x 31 columns]

In [ ]:
new_data = data.apply(abs)
new_data
# new_data.isnull().sum().sum()

       Time        V1        V2  ...       V28      Amount     Class
0         0  1.359807  0.072781  ...  0.021053  149.620000  0.000000
1         0  1.191857  0.266151  ...  0.014724    2.690000  0.000000
2         1  1.358354  1.340163  ...  0.059752  378.660000  0.000000
3         1  0.966272  0.185226  ...  0.061458  123.500000  0.000000
4         2  1.158233  0.877737  ...  0.215153   69.990000  0.000000
...     ...       ...       ...  ...       ...         ...       ...
9960  14837  1.286884  0.124610  ...  0.022744   12.180000  0.000000
9961  14854  1.318742  0.496408  ...  0.017304    1.780000  0.000000
9962  14857  1.241757  0.419587  ...  0.017208    1.290000  0.000000
9963  14861  1.304800  0.052885  ...  0.015404    4.720000  0.000000
9964  14864  1.747939  3.712444  ...  0.003051   62.968359  0.003814

[9965 rows x 31 columns]

In [ ]:


# from sklearn.preprocessing import LabelEncoder
# lbl = LabelEncoder()
# X = lbl.fit_transform(x).reshape(1)
# X

Time        int64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
dtype: object

In [ ]:
new_data = pd.get_dummies(new_data)

       Time        V1        V2  ...       V28      Amount     Class
0         0  1.359807  0.072781  ...  0.021053  149.620000  0.000000
1         0  1.191857  0.266151  ...  0.014724    2.690000  0.000000
2         1  1.358354  1.340163  ...  0.059752  378.660000  0.000000
3         1  0.966272  0.185226  ...  0.061458  123.500000  0.000000
4         2  1.158233  0.877737  ...  0.215153   69.990000  0.000000
...     ...       ...       ...  ...       ...         ...       ...
9960  14837  1.286884  0.124610  ...  0.022744   12.180000  0.000000
9961  14854  1.318742  0.496408  ...  0.017304    1.780000  0.000000
9962  14857  1.241757  0.419587  ...  0.017208    1.290000  0.000000
9963  14861  1.304800  0.052885  ...  0.015404    4.720000  0.000000
9964  14864  1.747939  3.712444  ...  0.003051   62.968359  0.003814

[9965 rows x 31 columns]

In [ ]:
x = new_data.iloc[:,:-1]
x
y = new_data[['Class']]
y 
x.dtypes

Time        int64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
dtype: object

In [ ]:
x.isnull().sum().sum()
x.isna().sum().sum()
x.isin(['-']).sum().sum()

In [ ]:
from sklearn.feature_selection import  SelectKBest
from sklearn.feature_selection import  chi2
best_features = SelectKBest(score_func=chi2,k=10)
fit =  best_features.fit(x,y)
fit

In [ ]:
data_score = pd.DataFrame(fit.scores_)
data_score
data_col = pd.DataFrame(x.columns)
data_col

         0
0     Time
1       V1
2       V2
3       V3
4       V4
5       V5
6       V6
7       V7
8       V8
9       V9
10     V10
11     V11
12     V12
13     V13
14     V14
15     V15
16     V16
17     V17
18     V18
19     V19
20     V20
21     V21
22     V22
23     V23
24     V24
25     V25
26     V26
27     V27
28     V28
29  Amount

In [ ]:
fs = pd.concat([data_col,data_score],axis=1)
fs.columns = ['V1','V2']
print(fs.nlargest(1,'V2'))

Empty DataFrame
Columns: [V1, V2]
Index: []